name: Clone Repo

on:
  workflow_dispatch:
    inputs:
      vps_path:
        description: 'Path on VPS'
        required: true
        default: '.'

        
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connect VPS & Clone
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p ${{ github.event.inputs.vps_path }}
            cd ${{ github.event.inputs.vps_path }}
            pwd
            git clone ${{ github.repositoryUrl }}
            cd ${{ github.event.repository.name }}
            pwd
          
