name: Django Install, Migrate, Run

on:
  workflow_dispatch: 
      inputs:
        vps_path:
          description: 'Repo Parent Path on VPS'
          required: true
          default: './'
        django_pro_path:
          description: 'Django Project Path in Repo'
          required: true
          default: './'
        venv_name:
          description: 'Virtual Env Name'
          required: true
          default: venv
        run_port:
          description: 'Running port'
          required: true
          default: 8000

        
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connect VPS & Clone
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p ${{ github.event.inputs.vps_path }}
            cd ${{ github.event.inputs.vps_path }}
            pwd
            git clone ${{ github.repositoryUrl }}
            cd ${{ github.event.repository.name }}
            pwd
            python -m venv ${{ github.event.inputs.venv_name }}
            source ${{ github.event.inputs.venv_name }}/bin/activate
            pip install -r requirements.txt
            pip install gunicorn
            python manage.py makemigrations
            python manage.py migrate
            fuser -n tcp -k ${{ github.event.inputs.run_port }}
            gunicorn helloapp.wsgi --bind 0.0.0.0:${{ github.event.inputs.run_port }} --daemon
            ps ax|grep gunicorn
            
